// <auto-generated />
using DemoMVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.DataAccess.Migrations.HtmlDb
{
    [DbContext(typeof(HtmlDbContext))]
    partial class HtmlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoMVC.Models.Html.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CSS_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CSS_Class = "",
                            Icon = "",
                            ParentId = 0,
                            Sequence = 1,
                            Title = "Home",
                            URL = "/"
                        },
                        new
                        {
                            Id = 2,
                            CSS_Class = "",
                            Icon = "",
                            ParentId = 0,
                            Sequence = 2,
                            Title = "Content Management",
                            URL = "/"
                        },
                        new
                        {
                            Id = 3,
                            CSS_Class = "",
                            Icon = "",
                            ParentId = 2,
                            Sequence = 1,
                            Title = "Category",
                            URL = "/"
                        },
                        new
                        {
                            Id = 4,
                            CSS_Class = "",
                            Icon = "",
                            ParentId = 2,
                            Sequence = 2,
                            Title = "Cover Type",
                            URL = "/"
                        },
                        new
                        {
                            Id = 5,
                            CSS_Class = "",
                            Icon = "",
                            ParentId = 2,
                            Sequence = 3,
                            Title = "Product",
                            URL = "/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
